#!/bin/bash

while [ `kubectl get pv | grep -c ^pvc` -gt 0 ];do
   for PV in `kubectl get pv | grep ^pvc | awk '{print $1}'`;do
      kubectl delete pv $PV &
      kubectl patch pv $PV -p '{"metadata":{"finalizers":null}}'
      sleep 2
   done
done

