#!/bin/bash

#set -e
#set -x

. failover_lib

echo Test set up unique ID: $$
echo All generated k8s config files can be found in $TMPDIR
echo

# High level steps:
# 1. Establish replication, wait for data to be mirrored
# 2. Split mirror and mount velero PVC
# 3. Install velero on peer
# 4. Restore
#

# 1
update_primary
#start_rep 
pred "waiting replication to be complete ..."
sleep 20

# 2
stop_rep

# 3 
prepare_remote

# 4
restore
