#!/bin/bash

echo execute this script on a k8s node with ceph nodes injected into /etc/hosts

CEPHA='ceph3-1'
CEPHB='ceph4-1'
#OUTPUT=/devhub/fksdr/template/csi-config-map-$$.yaml
OUTPUT=/devhub/fksdr/template/csi-config-map.yaml

gen_segment()
{
   FSID="`ssh $1 cat /etc/ceph/ceph.conf | grep fsid | awk '{print $3}'`"
   IP="`grep $1 /etc/hosts | awk '{print $1}'`"
   cat <<EOF
        "clusterID": "$FSID",
        "monitors": [
          "$IP:6789",
          "$IP:6789",
        ]
EOF
}

SEGA="`gen_segment $CEPHA`"
SEGB="`gen_segment $CEPHB`"

#cat /devhub/fksdr/template/csi-config-map.yaml.template | sed "s/FSID/$FSID/g;s/IP/$IP/g" | tee $OUTPUT

cat > $OUTPUT <<EOF
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
$SEGA
      },
      {
$SEGB
      },
    ]
metadata:
  name: ceph-csi-config
  namespace: ceph-csi-rbd

EOF

