#!/bin/bash

CEPHA=ceph3-1
CEPHB=ceph4-1

ssh $CEPHA apt install -y rbd-mirror
ssh $CEPHB apt install -y rbd-mirror
ssh $CEPHA 'echo CLUSTER=site-a >> /etc/default/ceph'
ssh $CEPHB 'echo CLUSTER=site-b >> /etc/default/ceph'

ssh $CEPHA "ceph auth get-or-create client.site-a mon 'profile rbd' osd 'profile rbd pool=data' -o /etc/ceph/site-a.client.site-a.keyring"
ssh $CEPHB "ceph auth get-or-create client.site-b mon 'profile rbd' osd 'profile rbd pool=data' -o /etc/ceph/site-b.client.site-b.keyring"

ssh $CEPHA ln -s /etc/ceph/ceph.conf /etc/ceph/site-a.conf
ssh $CEPHB ln -s /etc/ceph/ceph.conf /etc/ceph/site-b.conf
scp $CEPHA:/etc/ceph/ceph.conf /tmp/site-a.conf
scp /tmp/site-a.conf $CEPHB:/etc/ceph/site-a.conf
scp $CEPHA:/etc/ceph/site-a.client.site-a.keyring /tmp/
scp /tmp/site-a.client.site-a.keyring $CEPHB:/etc/ceph/
scp $CEPHB:/etc/ceph/ceph.conf /tmp/site-b.conf
scp /tmp/site-b.conf $CEPHA:/etc/ceph/
scp $CEPHB:/etc/ceph/site-b.client.site-b.keyring /tmp/
scp /tmp/site-b.client.site-b.keyring $CEPHA:/etc/ceph/

ssh $CEPHB systemctl enable ceph-rbd-mirror.target
ssh $CEPHB systemctl enable ceph-rbd-mirror@site-b
ssh $CEPHB systemctl start ceph-rbd-mirror@site-b

ssh $CEPHA rbd mirror pool enable data pool
ssh $CEPHB rbd mirror pool enable data pool
ssh $CEPHB rbd --cluster site-b mirror pool peer add data client.site-a@site-a -n client.site-b

