#!/bin/bash

if $# -ne 1;then exit;fi

ID=$1

# ==============================================================================================
#         Update to match test environment, do not change anything else

CEPHA=ceph3-1
CEPHB=ceph4-1
PEER=testk8s-1

# ==============================================================================================

set -e

echo Test set up unique ID: $ID
echo

TMPDIR=/devhub/fksdr/tmp/$ID
mkdir -p $TMPDIR
pushd $TMPDIR

PVC=pvc-$ID
POD=nginx-$ID

PVID="`kubectl get pv | grep vtest/$PVC | awk '{print $1}'`"
VOLID="`kubectl get pv $PVID -o yaml | grep "^  *imageName:" | awk '{print $2}'`"
kubectl delete pod $POD -n vtest
kubectl delete pvc $PVC -n vtest
kubectl delete pv $PVID

PVID="`ssh $PEER kubectl get pv | grep vtest/$PVC | awk '{print $1}'`"
ssh $PEER kubectl delete pod $POD -n vtest
ssh $PEER kubectl delete pvc $PVC -n vtest
ssh $PEER kubectl delete pv $PVID
ssh $CEPHB rbd mirror image promote data/$VOLID
ssh $CEPHB rbd mirror image promote data/$VOLID
ssh $CEPHA rbd rm data/$VOLID

